### ISSUE TITLE
hi,  can I exported the onnx model without doing QAT

### ISSUE THREAD

**Issue by ynma-hanvo** [MengmengXiao/Quantization_pytorch_tensorrt#1]
hi, I am actually doing the same thing on a network.
but I am not very understand the QAT process ,    
is it able to export onnx from just after the PTQ  step and run it in tensorrt. 
is the pytroch-quantization PTQ   sames as tensorrt PTQ ?

**Comment by MengmengXiao** [comment]
Hi, @ynma-hanvo, 
- is it able to export onnx from just after the PTQ step and run it in tensorrt. --> Sure, QAT is not a must.
- is the pytroch-quantization PTQ sames as tensorrt PTQ ? --> No, they are quite different. According to my experience in quantization, if you want to do model compression on a certain type of hardware (like NV Jetson), you have to follow the corresponding toolkit for quantization (tensorrt pytorch-quantization). The reason is each company has its own algorithm of quantization optimization.

In addition, I highly recommend this [paper](https://arxiv.org/pdf/2106.08295.pdf) that manifests a comprehensive process of PTQ and QAT. Hope my answer helpful!

**Comment by ynma-hanvo** [comment]
thanks for the explanation.

**Comment by ynma-hanvo** [comment]
hello,  following the pytorch-quantization  , I can not exported the calibrated model into onnx as I failed to upgrade to pytorch-quantization==2.2.0,  which is not on nvidia pypi ;
do you have any experience with exporting the pytorch-quantization calibrated model into onnx?

**Comment by MengmengXiao** [comment]
Hi @ynma-hanvo,
My version of pytorch-quantization is 2.1.3 and I convert PTQ/QAT .pth model to onnx format successfully by running **python quantization_code/convert_onnx.py** in this repository. 
When I faced this converting issue, I took https://github.com/NVIDIA/TensorRT/issues/3219#issue-1851352797 for reference and it turn out to be workable for me. So rather than upgrading the pytorch-quantization version to 2.2.0, I changed my exporting code to suit my current version to fix the problem.

**Comment by ynma-hanvo** [comment]
> Hi @ynma-hanvo, My version of pytorch-quantization is 2.1.3 and I convert PTQ/QAT .pth model to onnx format successfully by running **python quantization_code/convert_onnx.py** in this repository. When I faced this converting issue, I took [NVIDIA/TensorRT#3219 (comment)](https://github.com/NVIDIA/TensorRT/issues/3219#issue-1851352797) for reference and it turn out to be workable for me. So rather than upgrading the pytorch-quantization version to 2.2.0, I changed my exporting code to suit my current version to fix the problem.

thanks very much.   I  did export the onnx successfully. 
do you know the different between 'histogram' and 'max'  calib_method?

**Comment by MengmengXiao** [comment]
Hi @ynma-hanvo, 
We all know that the core of quantization is about determining 2 values for tensor, that is, **scale** and **zero_point**. 'Histogram' and 'max' methods are both statistic algorithms to find a **scale**. If there are outliers in tensor, using histogram statistic method to settle down the scale is more reasonable for a better accuracy with entropy/ percentile /mse. Otherwise, it's ok to use 'max' simply to save calculation consumption and get a pretty good result.
The above is the general differences between two methods. As for the implementation details in tensorrt,  it's available to see the open-sourced code and get a deep understanding. Hope my answer useful to you.

**Comment by ynma-hanvo** [comment]
@MengmengXiao   I intended to use histogram but failed with messages about " can not convert inf to integer".
so I can only use the max method which is fine.     thanks very much. I am now more clear about this calibration and quantization topics;
